Numpy Basics Practice Day 1

In [6]:
import numpy as np

In [7]:
np.__version__

'1.26.4'

In [8]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

# Convert List into Array using Numpy
## Three ways: np.array, np.asarray, np.asanyarray

In [12]:
l=[1,2,3,4,5,6]
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [13]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [14]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

# Type- DataType of numpy array and check dimension

In [15]:
type(np.array(l))

numpy.ndarray

In [22]:
a=np.array(l)
print(a.ndim)
a

1


array([1, 2, 3, 4, 5, 6])

In [26]:
l = [1, 2, 3, 4, 5, "Rishi"]
arr1 = np.array(l)
#here as there is string present in the list that is being converted into array so datatype of each element in the array is converted to string
arr1

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U11')

# 2 D Array

In [32]:
l =[[1,2,3],[4,5,6],[7,8,9]]
s=[[1,2,'stree'],[4,5,6],[7,8,9]]
a=np.array(l)
b=np.array(s)
print(a)
print(a.ndim)
print(type(a))
print(b)
print(b.ndim)
print(type(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
<class 'numpy.ndarray'>
[['1' '2' 'stree']
 ['4' '5' '6']
 ['7' '8' '9']]
2
<class 'numpy.ndarray'>


# Convert a list into Matrix
## Matrix by default is a 2D array
### Matrix is subset of array

In [33]:
l=[1,2,3,4]
mat=np.matrix(l)
print(mat)
print(mat.ndim)

[[1 2 3 4]]
2


In [34]:
# will throw error when a 3d list is converted to matrix but in case of np.array the same will work

In [35]:
np.matrix([[[1, 2], [5, 6], [7, 8]]])

ValueError: matrix must be 2-dimensional

In [36]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

#  np.asanyarray
## Convert the input to an ndarray, but pass ndarray subclasses through.

In [39]:
np.asanyarray([[[1, 2], [5, 6], [7, 8]]]) 

#Convert the input to an ndarray, but pass ndarray subclasses through.

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [40]:
l=[1,2,3,4]
mat=np.matrix(l)
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

# Convert Tuple into Array

In [41]:
t=([1,2,3],[4,5,6])
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

# Convert Variable into Array

In [42]:
a=5
np.array(a)

array(5)

# Shallow copy and Deep Copy

In [44]:
# Shallaw copy: whenever changes in one array changes values in another array
a=np.array([1,2,3,4,5])
b=a
a[0]=10
print(b)

[10  2  3  4  5]


In [49]:
# Deep copy: whenever changes in one array doesn't changes values in another array
a=np.array([1,2,3,4,5])
b=a.copy()
b[0]=10
a[4]=22
print("a is:",a )
print("b is:",b)

a is: [ 1  2  3  4 22]
b is: [10  2  3  4  5]


# Ways of Generating Arrays
### 1. np.fromfunction
### 2. np.fromiter
### 3. np.fromstring

In [50]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [51]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [52]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [59]:
iterable=(i for i in range(10) if i%2==0)

In [60]:
np.fromiter(iterable, int)

array([0, 2, 4, 6, 8])

In [63]:
np.fromstring('12,34,54',sep=',',dtype=int)

array([12, 34, 54])

In [64]:
np.fromstring('12 34 54',sep=' ',dtype=int)

array([12, 34, 54])

In [66]:
np.fromstring('Dyuti,Bitan,ChotoBunu',sep=',')

C:\Users\DYUTI SUNDER DUTTA\AppData\Local\Temp\ipykernel_16104\3640688810.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Dyuti,Bitan,ChotoBunu',sep=',')


array([], dtype=float64)

# Size and shape and datatype of element of array

In [78]:
a=np.array([1,2,3,4,5])
print(a.shape)
print(a.size)
print(a.dtype)

(5,)
5
int32


In [75]:
a=np.array([[1,2,3,4,5]])
print(a.shape)
print(a.size)

(1, 5)
5


In [77]:
a=np.array([[1,2,3,4,'stree'],[1,2,3,4,5],[1,2,3,4,5]])
print(a.shape)
print(a.size)
print(a.dtype)

(3, 5)
15
<U11


# List Comprehension and Range function

In [80]:
[i for i in range(1,50) if i%3==0]

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

In [81]:
list([i for i in range(1,50) if i%3==0])

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

In [83]:
list(range(3,50,3))

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

In [85]:
print(range(0,5,1))
print(list(range(0,5,1)))

range(0, 5)
[0, 1, 2, 3, 4]


In [87]:
#range doesnot supports float values
range(1.0,5.0)

TypeError: 'float' object cannot be interpreted as an integer

# np.arange
### generates array between range with step as mentioned or default 1

In [95]:
l= np.arange(0,0.5,0.1)
l

array([0. , 0.1, 0.2, 0.3, 0.4])

# np.linspace
### generates array between range, the values are equidistant and count of value generated is equivalent to the third parameter

In [93]:
l=np.linspace(0,10,20)
print(l)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


# np.logspace 


In [97]:
l=np.logspace(0,10, 5, base =2)
print(l)

[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]


In [98]:
l=np.logspace(0,10, 10, base =10)
print(l)

[1.00000000e+00 1.29154967e+01 1.66810054e+02 2.15443469e+03
 2.78255940e+04 3.59381366e+05 4.64158883e+06 5.99484250e+07
 7.74263683e+08 1.00000000e+10]


# Zeros and Ones Array

In [100]:
a=np.zeros(6, dtype=int)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[0 0 0 0 0 0]
(6,)
1
int32


In [101]:
a=np.zeros((3,4), dtype=int)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
2
int32


In [102]:
a=np.ones((3,4), dtype=int)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)
2
int32


In [104]:
a=np.ones((1,1,1,1,1,3,4), dtype=int)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[[[[[[1 1 1 1]
      [1 1 1 1]
      [1 1 1 1]]]]]]]
(1, 1, 1, 1, 1, 3, 4)
7
int32


In [106]:
b=a*3
c=a+10
print(b)
print(c)

[[[[[[[3 3 3 3]
      [3 3 3 3]
      [3 3 3 3]]]]]]]
[[[[[[[11 11 11 11]
      [11 11 11 11]
      [11 11 11 11]]]]]]]


Numpy Practice Day 2

# np.empty , np.eye 


In [114]:
# np.empty generates random array element
np.empty((3,4), dtype=int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 4456540, 5570649],
       [4784212, 8257619,      49, 3342437]])

In [115]:
#np.eye generates identity array
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Random library
1. random.choice
2. random.randrange
3. random.random
4. random.shuffle
5. random.uniform

In [135]:
import random
l=[4,9,8,7,5]
print(random.choice([1,2,3,4,'122']))
print(random.choice((1,2,3,4,'122')))

print(random.randrange(1,10))
print(random.random())

4
122
6
0.705216256518935


In [136]:
y=random.shuffle(l)

In [137]:
print(y)

None


In [138]:
random.uniform(7,14)

13.397442980224977

# Random in numpy Library
1. np.random.rand
2. np.random.randn
3. np.random.random_sample
4. np.random.randint

In [139]:
np.random.rand(1)

array([0.5097573])

In [142]:
np.random.rand(2,3)

array([[0.35974844, 0.28385437, 0.9921468 ],
       [0.2915496 , 0.80326681, 0.35409207]])

In [143]:
np.random.randn(2,3)

array([[ 0.5451873 ,  1.33137012,  0.27579288],
       [-1.37288257,  0.70753053,  1.23679692]])

In [151]:
np.random.random_sample(5)

array([0.07917959, 0.67704256, 0.34466322, 0.51918492, 0.39765306])

In [154]:
np.random.randint(1,5, size=(2,3))

array([[3, 3, 2],
       [2, 2, 2]])

# Reshaping Array

In [161]:
l=[[1,2,3,4],[1,4,5,7],[6,7,8,9]]
a=np.array(l)
a.shape

(3, 4)

In [162]:
a.reshape(1,12)

array([[1, 2, 3, 4, 1, 4, 5, 7, 6, 7, 8, 9]])

In [163]:
a.reshape(6,2)

array([[1, 2],
       [3, 4],
       [1, 4],
       [5, 7],
       [6, 7],
       [8, 9]])

In [164]:
a.reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [165]:
#while reshaping the shape of the array should be multiplicable of the original array

In [167]:
a.reshape(-1,12)

array([[1, 2, 3, 4, 1, 4, 5, 7, 6, 7, 8, 9]])

In [168]:
a.reshape(-1,6)

array([[1, 2, 3, 4, 1, 4],
       [5, 7, 6, 7, 8, 9]])

In [170]:
# if we put one of the reshaping parameter as negative, then numpy will automatically calculate the suitable value that 
# needs to fit in place of that negative value to correctly reshape the array


In [171]:
a.reshape(-1,6).base

array([[1, 2, 3, 4],
       [1, 4, 5, 7],
       [6, 7, 8, 9]])

In [172]:
# in order to revert back to the original shape use .base

In [174]:
a.reshape(1,1,1,1,2,6)

array([[[[[[1, 2, 3, 4, 1, 4],
           [5, 7, 6, 7, 8, 9]]]]]])

In [175]:
# the dimension of an array can be increased untill the changed shape is a multiplicable of the original shape

# Filter Array

In [178]:
l=[[1,2,3,4],[1,4,5,7],[6,7,8,9]]
arr1=np.array(l)
arr1

array([[1, 2, 3, 4],
       [1, 4, 5, 7],
       [6, 7, 8, 9]])

In [181]:
arr1[arr1>1]
# returns all the values in 1 d array

array([2, 3, 4, 4, 5, 7, 6, 7, 8, 9])

# Accessing Array Elements

In [182]:
arr1

array([[1, 2, 3, 4],
       [1, 4, 5, 7],
       [6, 7, 8, 9]])

In [185]:
arr1[0][1]
#first row 2nd column

2

In [188]:
arr1[:][1]
# 2nd row

array([1, 4, 5, 7])

In [190]:
arr1[:][0]
# 1st Row

array([1, 2, 3, 4])

In [191]:
arr1[1][:]
# 2nd row

array([1, 4, 5, 7])

In [193]:
arr1[2][:]
# 3rd row

array([6, 7, 8, 9])

In [194]:
arr1[0,1]

2

In [195]:
arr1

array([[1, 2, 3, 4],
       [1, 4, 5, 7],
       [6, 7, 8, 9]])

In [197]:
arr1[:,0]
#all row, 1st column

array([1, 1, 6])

In [198]:
arr1[0,:]
#all column, 1st row

array([1, 2, 3, 4])

In [199]:
arr1[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [200]:
arr1[1:3,-1]

array([7, 9])

In [201]:
arr1[[1,2],[1,2]]

array([4, 8])

In [208]:
arr1[0:3,[1,3]]

array([[2, 4],
       [4, 7],
       [7, 9]])

# Adding , Substracting, Multiplying, Dividing two arrays

In [213]:
arr1=np.random.randint(1,10,(3,4),dtype=int)
arr2=np.random.randint(1,10,(3,4),dtype=int)

In [215]:
print(arr1)
print(arr2)

[[4 6 1 5]
 [6 7 9 7]
 [8 6 9 6]]
[[9 5 9 8]
 [8 9 1 8]
 [6 5 2 4]]


In [216]:
arr1+arr2

array([[13, 11, 10, 13],
       [14, 16, 10, 15],
       [14, 11, 11, 10]])

In [221]:
arr1-arr2

array([[-5,  1, -8, -3],
       [-2, -2,  8, -1],
       [ 2,  1,  7,  2]])

In [217]:
arr1*arr2

array([[36, 30,  9, 40],
       [48, 63,  9, 56],
       [48, 30, 18, 24]])

In [218]:
arr1/arr2

array([[0.44444444, 1.2       , 0.11111111, 0.625     ],
       [0.75      , 0.77777778, 9.        , 0.875     ],
       [1.33333333, 1.2       , 4.5       , 1.5       ]])

In [219]:
arr1%arr2

array([[4, 1, 1, 5],
       [6, 7, 0, 7],
       [2, 1, 1, 2]])

In [220]:
arr1/0

C:\Users\DYUTI SUNDER DUTTA\AppData\Local\Temp\ipykernel_16104\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

# Matrix Multiplication

In [223]:
arr1

array([[4, 6, 1, 5],
       [6, 7, 9, 7],
       [8, 6, 9, 6]])

In [233]:
arr2=arr2.reshape(4,3)
arr2

array([[9, 5, 9],
       [8, 8, 9],
       [1, 8, 6],
       [5, 2, 4]])

In [234]:
arr1.shape

(3, 4)

In [235]:
arr2.shape

(4, 3)

In [228]:
# column count of first matrix and row count of second matrix should be same for matrix multiplication
# the output of which will be row count of first matrix cross column count of second matrix

In [236]:
arr1@arr2

array([[110,  86, 116],
       [154, 172, 199],
       [159, 172, 204]])

# Broadcasting

In [239]:
arr=np.zeros((2,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [240]:
arr2=arr+3
arr2

array([[3, 3, 3],
       [3, 3, 3]])

In [241]:
arr3=np.array([1,2,3])

In [242]:
arr4=arr2+arr3

In [243]:
arr4

array([[4, 5, 6],
       [4, 5, 6]])

In [244]:
arr5=np.array([1,2,3,4])
arr6=arr4+arr5

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

# Square root, Exponential, Minimum, Maximum, sum using numpy

In [245]:
np.sqrt(arr1)

array([[2.        , 2.44948974, 1.        , 2.23606798],
       [2.44948974, 2.64575131, 3.        , 2.64575131],
       [2.82842712, 2.44948974, 3.        , 2.44948974]])

In [246]:
np.exp(arr1)

array([[5.45981500e+01, 4.03428793e+02, 2.71828183e+00, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 8.10308393e+03, 1.09663316e+03],
       [2.98095799e+03, 4.03428793e+02, 8.10308393e+03, 4.03428793e+02]])

In [248]:
np.log2(arr1)

array([[2.        , 2.5849625 , 0.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.169925  , 2.80735492],
       [3.        , 2.5849625 , 3.169925  , 2.5849625 ]])

In [249]:
np.min(arr1)

1

In [250]:
np.max(arr1)

9

In [251]:
np.mean(arr1)

6.166666666666667

In [252]:
np.std(arr1)

2.1147629234082532

In [253]:
np.var(arr1)

4.472222222222222

In [254]:
np.sum(arr1)

74

In [257]:
np.sum(arr1, axis=1)

array([16, 29, 29])

In [258]:
np.sum(arr1, axis=0)

array([18, 19, 19, 18])

In [260]:
np.mean(arr1, axis=1)

array([4.  , 7.25, 7.25])

# Flatten ->
Reduces higher dimensional arrays into 1 D array

In [256]:
arr1.flatten()

array([4, 6, 1, 5, 6, 7, 9, 7, 8, 6, 9, 6])

# Expand_dims -->
Expands the dimension of the array by inserting new axis

In [261]:
l=[1,2,3,4]
arr=np.array(l)

In [262]:
arr

array([1, 2, 3, 4])

In [269]:
arr1=np.expand_dims(arr, axis=1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [270]:
arr1=np.expand_dims(arr, axis=0)
arr1

array([[1, 2, 3, 4]])

In [272]:
arr2=np.expand_dims(arr1, axis=0)
arr2

array([[[1, 2, 3, 4]]])

In [273]:
arr=np.zeros((2,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [274]:
a=np.expand_dims(arr,axis=1)
a

array([[[0, 0, 0]],

       [[0, 0, 0]]])

In [275]:
b=np.expand_dims(arr,axis=0)
b

array([[[0, 0, 0],
        [0, 0, 0]]])

# Squeeze
it reduces one dimension from the numpy array

In [280]:
arr=np.ones((1,1,4,3),dtype=int)
arr
arr.ndim

4

In [281]:
a=np.squeeze(arr)
a.ndim

2

# Repeat

In [283]:
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [285]:
np.repeat(a,2)
#each element is repeated twice and the array is converted to 1 dimension

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 8, 8])

In [286]:
np.repeat(a,2, axis =1)

array([[1, 1, 2, 2, 3, 3],
       [4, 4, 5, 5, 6, 6],
       [6, 6, 7, 7, 8, 8]])

In [287]:
np.repeat(a,2, axis =0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [6, 7, 8],
       [6, 7, 8]])

# Roll
shuffles the position of row values by the parameter provided

In [289]:
data=np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [294]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [295]:
data=np.array([[1,2],[2,3],[3,4]])
data

array([[1, 2],
       [2, 3],
       [3, 4]])

In [296]:
np.roll(data, 2)

array([[3, 4],
       [1, 2],
       [2, 3]])

# Bitwise Negation
--> negative(value - 1)

In [298]:
~data

array([[-2, -3],
       [-3, -4],
       [-4, -5]])

# Numpy String Function
1. Uppercase
2. Capitalize
3. Title

In [312]:
arr=np.array(['PW is good','SKILLS'])

In [313]:
arr

array(['PW is good', 'SKILLS'], dtype='<U10')

In [314]:
np.char.upper(arr)

array(['PW IS GOOD', 'SKILLS'], dtype='<U10')

In [315]:
np.char.lower(arr)

array(['pw is good', 'skills'], dtype='<U10')

In [316]:
np.char.capitalize(arr)

array(['Pw is good', 'Skills'], dtype='<U10')

In [317]:
np.char.title(arr)

array(['Pw Is Good', 'Skills'], dtype='<U10')

# Numpy Mathematical Function

In [333]:
data=np.random.randint(2,10,(2,3),dtype=int)
data1=np.random.randint(2,10,(2,3),dtype=int)

In [322]:
np.sin(data)

array([[ 0.90929743, -0.7568025 , -0.95892427],
       [ 0.98935825,  0.14112001,  0.90929743]])

In [323]:
np.cos(data)

array([[-0.41614684, -0.65364362,  0.28366219],
       [-0.14550003, -0.9899925 , -0.41614684]])

In [324]:
np.log10(data)

array([[0.30103   , 0.60205999, 0.69897   ],
       [0.90308999, 0.47712125, 0.30103   ]])

In [325]:
np.sqrt(data)

array([[1.41421356, 2.        , 2.23606798],
       [2.82842712, 1.73205081, 1.41421356]])

In [326]:
np.exp(data)

array([[   7.3890561 ,   54.59815003,  148.4131591 ],
       [2980.95798704,   20.08553692,    7.3890561 ]])

In [328]:
np.power(data,2)

array([[ 4, 16, 25],
       [64,  9,  4]], dtype=int32)

In [329]:
np.mean(data)

4.0

In [330]:
np.max(data)

8

In [331]:
np.std(data)

2.0816659994661326

In [332]:
np.var(data)

4.333333333333333

In [337]:
np.multiply(data,data1)

array([[63, 81, 45],
       [12, 24, 63]])

In [376]:
np.subtract(data, data1)

array([[ 2,  0, -4],
       [ 4,  2, -2]])

In [340]:
np.mod(data,data1)

array([[2, 0, 5],
       [0, 2, 7]])

# Sort and Search in 1D Array

In [341]:
arr=np.array([5,6,7,8,4,3,5])

In [342]:
np.sort(arr)

array([3, 4, 5, 5, 6, 7, 8])

In [353]:
np.searchsorted(arr,10)
#Find indices where elements should be inserted to maintain order.

7

# Find Non Zero Element

In [354]:
arr

array([5, 6, 7, 8, 4, 3, 5])

In [355]:
np.count_nonzero(arr)

7

# np.where
when condtion is passed, output is indices

In [356]:
np.where(arr>5)

(array([1, 2, 3], dtype=int64),)

# Extract Data where condition is passed
when condition is passed, output is the values

In [360]:
np.extract(arr>5, arr)

array([6, 7, 8])

# Convert Array to Byte representation

In [361]:
arr.byteswap()

array([ 83886080, 100663296, 117440512, 134217728,  67108864,  50331648,
        83886080])

# Matrix Library

In [364]:
import numpy.matlib as nm
nm.zeros(5, dtype=int)

matrix([[0, 0, 0, 0, 0]])

In [365]:
nm.ones((3,4),dtype=int)

matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

# Numpy Linear Algebra

In [367]:
a=np.random.randint(1,10,(3,3))
a

array([[3, 6, 8],
       [5, 4, 9],
       [3, 1, 3]])

In [372]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [373]:
np.linalg.solve(a,b)

array([ 1.96,  0.84, -1.24])

# Numpy Determinant of a Matrix

In [374]:
np.linalg.det(a)

24.999999999999996

# Numpy Inverse of a Matrix

In [375]:
np.linalg.inv(a)

array([[ 0.12, -0.4 ,  0.88],
       [ 0.48, -0.6 ,  0.52],
       [-0.28,  0.6 , -0.72]])